-- ============================================================
-- CRM-YG 空白后端建表脚本
-- 在 Supabase 项目 → SQL Editor 里整段粘贴运行即可。
-- 运行后数据库是「空白」的（没有任何客户/拜访/公海数据）。
-- ============================================================

-- ---------- 1. 用户档案表 profiles ----------
-- 每个登录账号对应一行；role = 'admin'(主管) 或 'sales'(业务员)
create table if not exists public.profiles (
  id         uuid primary key references auth.users(id) on delete cascade,
  name       text,
  role       text not null default 'sales',
  created_at timestamptz not null default now()
);

-- 注册时自动建立 profile（姓名取自注册时传入的 metadata.name，默认业务员）
create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer set search_path = public
as $$
begin
  insert into public.profiles (id, name, role)
  values (new.id, coalesce(new.raw_user_meta_data->>'name', new.email), 'sales')
  on conflict (id) do nothing;
  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
  after insert on auth.users
  for each row execute function public.handle_new_user();

-- ---------- 2. 潜在客户表 customers ----------
create table if not exists public.customers (
  id                uuid primary key,
  code_num          bigint generated by default as identity,
  name              text not null default '',
  owner_id          uuid,
  owner_name        text default '',
  is_public         boolean default false,
  stage             text default '潜在客户',
  attr              text default '',
  region            text default '',
  visited           text default '未拜访',
  contact           text default '',
  position          text default '',
  phone             text default '',
  trade_contact     text default '',
  trade_phone       text default '',
  shareholder       text default '',
  shareholder_phone text default '',
  product           text default '',
  address           text default '',
  source            text default '',
  platform_url      text default '',
  site_url          text default '',
  peer_case         text default '',
  note              text default '',
  create_date       date,
  next_follow       date,
  created_at        timestamptz not null default now()
);

-- ---------- 3. 拜访记录表 visits ----------
create table if not exists public.visits (
  id          uuid primary key,
  customer_id uuid,
  type        text default '拜访',
  title       text default '',
  visit_date  date,
  visitor     text default '',
  decider     text default '',
  position    text default '',
  phone       text default '',
  address     text default '',
  situation   text default '',
  result      text default '',
  next_follow date,
  a           text default '',
  m           text default '',
  n           text default '',
  t           text default '',
  company     text default '',
  owner       text default '',
  attr        text default '',
  signed      text default '',
  notes       text default '',
  product     text default '',
  created_at  timestamptz not null default now()
);

-- ---------- 4. 公海资料表 pool ----------
create table if not exists public.pool (
  id                uuid primary key,
  name              text not null default '',
  region            text default '',
  attr              text default '',
  contact           text default '',
  phone             text default '',
  product           text default '',
  address           text default '',
  source            text default '',
  platform_url      text default '',
  site_url          text default '',
  trade_contact     text default '',
  trade_phone       text default '',
  shareholder       text default '',
  shareholder_phone text default '',
  peer_case         text default '',
  create_date       date,
  origin            text default '',
  note              text default '',
  created_at        timestamptz not null default now()
);
-- 公海按公司名去重（前端也会去重，这里加唯一约束双保险）
create unique index if not exists pool_name_uniq on public.pool (name);

-- ============================================================
-- 5. 行级安全 (RLS)
-- 可见范围由前端按 owner/role 控制，云端对「已登录用户」放开读写。
-- ============================================================
alter table public.profiles  enable row level security;
alter table public.customers enable row level security;
alter table public.visits    enable row level security;
alter table public.pool      enable row level security;

-- profiles：登录用户可读全部；只能改自己的档案（主管建号时用后台更新姓名/角色）
drop policy if exists profiles_select on public.profiles;
create policy profiles_select on public.profiles for select to authenticated using (true);
drop policy if exists profiles_upsert on public.profiles;
create policy profiles_upsert on public.profiles for insert to authenticated with check (true);
drop policy if exists profiles_update on public.profiles;
create policy profiles_update on public.profiles for update to authenticated using (true) with check (true);

-- customers / visits / pool：登录用户全权读写
do $$
declare t text;
begin
  foreach t in array array['customers','visits','pool'] loop
    execute format('drop policy if exists %I_all on public.%I;', t, t);
    execute format('create policy %I_all on public.%I for all to authenticated using (true) with check (true);', t, t);
  end loop;
end $$;

-- ============================================================
-- 完成。接下来在 Authentication 里关掉「Confirm email」，
-- 然后注册第一个账号，再把它设为主管：
--   update public.profiles set role = 'admin', name = 'YG主管' where id = '<你的用户ID>';
-- ============================================================
