/* YG 公共资料区 → 公海客户（样本）
   来源：YG客户数据库 → 公共资料区 的 6 张表（史婕/赵孟菲/沈丹烨/林朱琦/李晶晶 潜在客户 + 优质大客户名单）。
   说明：6 张表合计数百条，因 Notion 批量导出需 Business 套餐，此处为示例样本；
   完整同步请在 Notion 把每张表「导出 CSV」后，用「数据管理 → 导入公海 CSV」上传（已适配各表表头，自动按公司去重）。 */
window.YG_POOL = {
  records: [
    {name:"宁波戴维医疗器械股份有限公司",region:"象山",attr:"",contact:"陈再宏",phone:"13906840137",product:"新生儿黄疸治疗仪、婴儿培养箱、婴儿辐射保暖台、经皮黄疸测定仪、医疗器械、SMT加工",address:"象山县石浦科技园区科苑路2号",source:"工商联系统通讯录",platformUrl:"",siteUrl:"",tradeContact:"刘总",tradePhone:"13738882006",createDate:"2026-06-04",origin:"优质大客户名单"},
    {name:"东方日升新能源股份有限公司",region:"宁海",attr:"",contact:"伍学纲",phone:"13736067199",product:"太阳能光伏、新能源",address:"",source:"工商联系统通讯录",platformUrl:"",siteUrl:"",tradeContact:"",tradePhone:"",createDate:"2026-06-04",origin:"优质大客户名单"},
    {name:"宁波纽新克电机有限公司",region:"市区",attr:"A+M+",contact:"罗千",phone:"13957636800",product:"电机、风机、无刷真空电机、无刷电机、无刷鼓风机",address:"浙江省宁波市鄞州区金谷中路（西）398号",source:"YG金品80条",platformUrl:"https://newthinkmotor.en.alibaba.com/",siteUrl:"http://www.newthinkmotor.com",tradeContact:"",tradePhone:"",createDate:"2026-03-19",origin:"史婕潜在客户（公共）"},
    {name:"宁波美乐雅荧光科技股份有限公司",region:"北仑",attr:"A+M-",contact:"陆明朗",phone:"13906683339",product:"收纳盒、礼品、荧光棒、泡泡水、画板、玩具、文具、户外照明、塑胶玩具",address:"浙江省宁波市北仑区小港街道渡头董立信路8号",source:"自查资料",platformUrl:"",siteUrl:"http://www.merryart.cn",tradeContact:"杜军杰",tradePhone:"13586560003",createDate:"2026-04-09",origin:"史婕潜在客户（公共）"},
    {name:"宁波卡儿酷玩具有限公司",region:"宁海",attr:"A+M-",contact:"林泽宇",phone:"15888572755",product:"儿童游戏屋、宠物用品、棉布、玩具、宠物帐篷、猫爬架、儿童帐篷、宠物窝、儿童围栏",address:"浙江省宁波市宁海县桃源街道金桥五路康尔·江南名都西侧约280米",source:"以前潜在资料",platformUrl:"",siteUrl:"",tradeContact:"",tradePhone:"",createDate:"2026-04-07",origin:"史婕潜在客户（公共）"},
    {name:"宁波爱浦工具有限公司",region:"市区",attr:"A+M+",contact:"章姚月",phone:"13757445469",product:"TIG火炬、米格/等离子火炬、焊接机、钨电极、焊棒、加热喷灯、暖通空调工具、焊接软管、户外烧烤套装",address:"宁波天童南路535号宏达大厦23a02室",source:"",platformUrl:"https://uppertools.en.alibaba.com/",siteUrl:"http://www.upperweld.com",tradeContact:"",tradePhone:"",createDate:"2026-03-24",origin:"赵孟菲潜在客户（公共）"},
    {name:"宁波永煦照明有限公司",region:"余姚",attr:"A+M-",contact:"赵文韬",phone:"13505746602",product:"LED照明",address:"宁波余姚市田屋路19号",source:"",platformUrl:"",siteUrl:"https://www.yonglux.com/",tradeContact:"徐成存（监事40%）",tradePhone:"13505746332",createDate:"2026-03-27",origin:"赵孟菲潜在客户（公共）"},
    {name:"余姚市祥和电器有限公司",region:"余姚",attr:"A+M-",contact:"陈波",phone:"13606596997",product:"电子元件、电子器件、电源充电器、模具、塑料制品、五金件",address:"浙江省余姚市临山镇临南新村10号",source:"",platformUrl:"",siteUrl:"http://www.nbxianghe.net/",tradeContact:"何冰（股东80%）",tradePhone:"",createDate:"2026-06-17",origin:"林朱琦潜在客户（公共）"},
    {name:"宁波市松林仪表有限公司",region:"慈溪",attr:"A+M-",contact:"吴仕林",phone:"18958353525",product:"制冷剂压力表、胶囊加压计、隔膜密封压力表、汽车保护工具、压力表、轮胎压力表、温度计",address:"慈溪市观海卫镇环城北路669号",source:"",platformUrl:"https://songlinyibiao.en.alibaba.com/",siteUrl:"",tradeContact:"",tradePhone:"",createDate:"2026-05-22",origin:"林朱琦潜在客户（公共）"},
    {name:"宁波五洲医疗器械有限公司",region:"余姚",attr:"A+M-",contact:"赵国珍",phone:"13805803268",product:"一次性脉冲冲洗器、麻醉呼吸回路、雾化器、指骨夹板、医疗器械、皮肤缝合器、医用夹板、注射器托架",address:"浙江省宁波市余姚市兰江街道磨刀桥路63-9号",source:"主管给的资料",platformUrl:"https://wzmedical.en.alibaba.com/",siteUrl:"http://www.fc-med.com",tradeContact:"",tradePhone:"",createDate:"2026-04-16",origin:"沈丹烨潜在客户（公共）"},
    {name:"宁波市精鸿阀门有限公司",region:"慈溪",attr:"A+M+",contact:"方兴亚",phone:"13857455743",product:"镀层天然液化石油气烹饪低压气体调节器",address:"慈溪市长河镇慈溪大道528号",source:"赵孟菲",platformUrl:"https://jinghongvalve.en.alibaba.com/",siteUrl:"",tradeContact:"张烨雯",tradePhone:"13968251619",createDate:"2026-03-27",origin:"李晶晶潜在客户（公共）"},
    {name:"宁波杰丽斯文具有限公司",region:"海曙",attr:"A+M-",contact:"张启文",phone:"18969816998",product:"切纸机系列、艺术用品、学生和office桌面产品、箱式存储类",address:"海曙区古林镇欧池工业区",source:"赵孟菲资料",platformUrl:"https://cnjielisi.en.alibaba.com/",siteUrl:"http://www.jielisi.com",tradeContact:"",tradePhone:"",createDate:"2026-03-16",origin:"史婕潜在客户（公共）"},
    {name:"余姚本色电器有限公司",region:"余姚",attr:"A+M-",contact:"刘辉",phone:"13968229275",product:"电推剪、理发器、鼻毛器、电动剃须刀、剃绒器",address:"浙江省宁波市余姚市低塘街道新洋路48号",source:"从前潜在",platformUrl:"",siteUrl:"",tradeContact:"",tradePhone:"",createDate:"2026-04-09",origin:"史婕潜在客户（公共）"},
    {name:"宁波宏立智能科技有限公司",region:"江北",attr:"A+M+",contact:"黄秀剑",phone:"13780017380",product:"家居家具、园艺家具、户外家具、帐篷和睡袋、健身器材",address:"浙江省江北区环城北路东段134号C-132",source:"YG资料",platformUrl:"https://dellabella.en.alibaba.com",siteUrl:"http://www.hollypro.com",tradeContact:"黄雪芳（监事）",tradePhone:"13616570746",createDate:"2026-03-24",origin:"史婕潜在客户（公共）"},
    {name:"宁波摩科电器有限公司",region:"市区",attr:"A+M+",contact:"徐波",phone:"18957888526",product:"真空吸尘器电机、冰箱定时器、洗衣机电机、家用电器、空气过滤器、齿轮箱",address:"浙江省宁波市鄞州区首南街道泰安中路177号天健巷70号2302室",source:"YG以前资料",platformUrl:"https://chinamoco.en.alibaba.com/",siteUrl:"http://www.china-moco.com",tradeContact:"徐世杰（AL海外）",tradePhone:"18352901019",createDate:"2026-03-30",origin:"史婕潜在客户（公共）"},
    {name:"宁波鑫球旅游用品有限公司",region:"北仑",attr:"A+M-",contact:"方爱萍",phone:"13362835055",product:"露营用品、各类帐篷",address:"北仑区龙角山路208号2幢1号3楼",source:"赵孟菲资料",platformUrl:"https://xinqiu-tent.en.alibaba.com/",siteUrl:"",tradeContact:"tent",tradePhone:"13082917110",createDate:"2026-03-16",origin:"史婕潜在客户（公共）"},
    {name:"梵秦科技(宁波)有限公司",region:"余姚",attr:"A+M-",contact:"秦君法",phone:"13336620269",product:"定时器插座、定时器开关、Wifi插座、Wifi开关、快速充电器",address:"浙江省宁波市余姚市兰江街道浙江远东工业城CN7",source:"以前潜在资料",platformUrl:"",siteUrl:"",tradeContact:"",tradePhone:"",createDate:"2026-04-07",origin:"史婕潜在客户（公共）"},
    {name:"宁波科诚休闲用品有限公司",region:"余姚",attr:"A+M+",contact:"冯彩戎",phone:"13968245188",product:"凉亭、佩戈拉、烧烤架、秋千",address:"浙江省余姚市兰江街道谭家岭西路1268号",source:"YG资料",platformUrl:"https://cxheshun.en.alibaba.com",siteUrl:"http://www.nbkozen.com",tradeContact:"沈（外贸高管）",tradePhone:"15067443767",createDate:"2026-03-24",origin:"史婕潜在客户（公共）"},
    {name:"宁波壹包进出口有限公司",region:"江北",attr:"A+M-",contact:"吕剑峰",phone:"13967815095",product:"针纺织品、冷藏包、生活用品、储物袋、旅行袋、鞋帽、背包、皮包",address:"宁波市江北区长兴路158号6号楼6601室",source:"YG以前同事的潜在客户资料",platformUrl:"https://one-bag.en.alibaba.com",siteUrl:"",tradeContact:"",tradePhone:"",createDate:"2026-03-24",origin:"史婕潜在客户（公共）"},
    {name:"宁波嘉利光电科技有限公司",region:"市区",attr:"A+M+",contact:"傅亮",phone:"13817300061",product:"放大镜灯、工作灯、落地灯、二极管",address:"宁波市市区星县路6号",source:"YG浴室配件",platformUrl:"https://jialibourya.en.alibaba.com/",siteUrl:"http://jialibourya.com",tradeContact:"",tradePhone:"",createDate:"2026-03-23",origin:"史婕潜在客户（公共）"},
    {name:"宁波长荣光电科技有限公司",region:"宁海",attr:"A+M+",contact:"胡海英",phone:"13506889816",product:"充电风扇、可充电照明产品",address:"浙江省宁波市宁海县西店镇五市路72号",source:"YG金品80条",platformUrl:"https://cnchangrong.en.alibaba.com/",siteUrl:"http://www.changrong.com.cn",tradeContact:"",tradePhone:"",createDate:"2026-03-19",origin:"史婕潜在客户（公共）"},
    {name:"慈溪市三叶文具有限公司",region:"慈溪",attr:"A+M-",contact:"严群娅",phone:"15314596816",product:"记号笔、白板笔、荧光笔、丙烯酸记号笔、颜料笔",address:"慈溪市观海卫镇昌兴村严家",source:"从前潜在资料",platformUrl:"",siteUrl:"",tradeContact:"",tradePhone:"",createDate:"2026-03-25",origin:"史婕潜在客户（公共）"},
    {name:"宁波东悦塑化有限公司",region:"余姚",attr:"A+M-",contact:"罗方（监事）",phone:"18606872712",product:"PETG、PA6、PP-R系列、填充母粒",address:"浙江省余姚市新建北路388号中国塑料城六号楼北-16#",source:"赵孟菲资料",platformUrl:"https://dongyueplastics.en.alibaba.com/",siteUrl:"",tradeContact:"",tradePhone:"",createDate:"2026-04-08",origin:"史婕潜在客户（公共）"},
    {name:"宁波合顺摩托车用品有限公司",region:"慈溪",attr:"A+M-",contact:"梅启元",phone:"15381888158",product:"摩托车零部件",address:"慈溪市龙山镇达蓬村东门桥路",source:"从前潜在资料",platformUrl:"",siteUrl:"",tradeContact:"",tradePhone:"",createDate:"2026-03-27",origin:"史婕潜在客户（公共）"},
    {name:"宁波雨桐国际贸易有限公司",region:"余姚",attr:"A+M-",contact:"潘孝燕",phone:"13780027096",product:"电动滑板车备件、电动滑板车轮胎、电动滑板车配件、电动滑板车、电动自行车",address:"浙江省宁波市余姚市凤山街道新建北路425号中塑世纪大厦1号楼613室",source:"以前潜在资料",platformUrl:"",siteUrl:"",tradeContact:"",tradePhone:"",createDate:"2026-04-07",origin:"史婕潜在客户（公共）"},
    {name:"宁波市科星管业发展有限公司",region:"余姚",attr:"A+M+",contact:"陈颖斐",phone:"13305845001",product:"聚丙烯配件、管道工具",address:"浙江省余姚市梨洲街道黄剑山工业区西三路4号",source:"赵孟菲资料",platformUrl:"https://kxpp-r.en.alibaba.com/",siteUrl:"http://www.kexingroup.com",tradeContact:"陈超",tradePhone:"13456106234",createDate:"2026-03-16",origin:"史婕潜在客户（公共）"},
    {name:"宁波惠隆佳泰家居用品有限公司",region:"",attr:"A+M-",contact:"纪玉成（执行董事70%）",phone:"13777084243",product:"加热角、低压热掷、电热毯、电热床垫、加热垫、冷却被子、电热披肩",address:"",source:"赵孟菲资料",platformUrl:"https://royalpeace.en.alibaba.com/",siteUrl:"http://nbroyalpeace.com",tradeContact:"纪鹏（外贸部）",tradePhone:"18357496383",createDate:"2026-04-08",origin:"赵孟菲潜在客户（公共）"},
    {name:"宁波天博急救用品有限公司",region:"海曙",attr:"A+M-",contact:"姜昊荣",phone:"13205748532",product:"急救包、急救生存包、生存包、户外急救包",address:"宁波市海曙区洞桥镇鱼山头村3号",source:"赵孟菲资料",platformUrl:"https://tbfirstaidkit.en.alibaba.com/",siteUrl:"http://www.tbfirstaid.com",tradeContact:"",tradePhone:"",createDate:"2026-03-24",origin:"赵孟菲潜在客户（公共）"},
    {name:"宁波市华膜环保科技有限公司",region:"市区",attr:"A+M-",contact:"王龙",phone:"13928114164",product:"测试仪器和设备、废水处理、水处理部件、预处理、膜和容器、EDI堆栈、反渗透系统",address:"宁波市泰康中路456号博纳大厦1008室",source:"赵孟菲资料",platformUrl:"https://nbhuamo.en.alibaba.com/",siteUrl:"http://www.huaromembrane.com",tradeContact:"",tradePhone:"",createDate:"2026-03-23",origin:"赵孟菲潜在客户（公共）"},
    {name:"宁波欧高儿童用品有限公司",region:"慈溪",attr:"A+M-",contact:"顾旦瑾",phone:"13957899724",product:"汽车儿童安全座椅、婴童安全座椅",address:"宁波慈溪市优高乐儿童用品有限公司2层",source:"赵孟菲资料",platformUrl:"",siteUrl:"",tradeContact:"",tradePhone:"",createDate:"2026-03-12",origin:"赵孟菲潜在客户（公共）"},
    {name:"慈溪奥历爵金属制品有限公司",region:"慈溪",attr:"A+M-",contact:"林建军",phone:"13805810555",product:"瓶顶、午餐盒上盖、托盘顶部、铝瓶、铝罐、铝杯、铝制饭盒、烤盘",address:"浙江省慈溪市龙山镇西门外村历帆路1号",source:"赵孟菲资料",platformUrl:"https://prodigy.en.alibaba.com/",siteUrl:"https://www.aolijue.com",tradeContact:"郑**（外贸部主管）",tradePhone:"18969805260",createDate:"2026-04-08",origin:"赵孟菲潜在客户（公共）"},
    {name:"宁波福帕思液压技术有限公司",region:"市区",attr:"A+M+",contact:"陈晓齐（60%）",phone:"18957800026",product:"液压电磁阀、液压电磁线圈、车用风门电磁阀、空气悬架阀块、多腔空气弹簧电磁阀",address:"宁波市鄞州区姜山科技园区夏施路5号",source:"赵孟菲资料",platformUrl:"https://nbfps.en.alibaba.com/",siteUrl:"http://www.fpas.com.cn",tradeContact:"外贸经理",tradePhone:"13396648930",createDate:"2026-03-19",origin:"赵孟菲潜在客户（公共）"},
    {name:"余姚市力阳包装制品有限公司",region:"余姚",attr:"A+M-",contact:"阮建平（执行董事50%）",phone:"13805808107",product:"滴油器、瓶子、精油盖、喷雾器",address:"浙江省余姚市万洋(黄家埠镇)众创城31幢",source:"赵孟菲资料",platformUrl:"",siteUrl:"",tradeContact:"",tradePhone:"",createDate:"2026-04-07",origin:"赵孟菲潜在客户（公共）"},
    {name:"宁波市铂莱斯特灌溉设备有限公司",region:"余姚",attr:"A+M+",contact:"陈超（法定代表人）",phone:"13456106234",product:"PP压缩接头、洒水器、夹具鞍座、盘式过滤器、球阀",address:"浙江省余姚市竹山桥万丰路1号",source:"赵孟菲资料",platformUrl:"https://irriplast.en.alibaba.com/",siteUrl:"http://www.irriplast.net",tradeContact:"陈颖斐（监事51%）",tradePhone:"13305845001",createDate:"2026-04-15",origin:"赵孟菲潜在客户（公共）"},
    {name:"宁波斯派沃通讯设备有限公司",region:"市区",attr:"A-M-",contact:"辛小静",phone:"15267850371",product:"网络机柜、服务器机柜、数据中心、壁柜、室外橱柜、开放式机架、PDU插座、橱柜配件、KVM",address:"宁波市鄞州区天童南路535号2807室",source:"赵孟菲资料",platformUrl:"https://nbstarlink.en.alibaba.com/",siteUrl:"https://www.starlink-comm.com/",tradeContact:"",tradePhone:"",createDate:"2026-03-04",origin:"赵孟菲潜在客户（公共）"},
    {name:"宁波寰帆进出口有限公司",region:"市区",attr:"A+M-",contact:"李总",phone:"18067359715",product:"促销品",address:"宁波市鄞州区泰康中路500号",source:"赵孟菲资料",platformUrl:"",siteUrl:"",tradeContact:"",tradePhone:"",createDate:"2026-03-13",origin:"赵孟菲潜在客户（公共）"},
    {name:"宁波孚泰安全胶条科技有限公司",region:"江北",attr:"A+M-",contact:"夏志武",phone:"18057473358",product:"安全边缘传感器、安全优势、橡胶轮廓、附属品、控制器",address:"浙江省宁波市江北区恒一大厦13-1-9",source:"赵孟菲资料",platformUrl:"https://safetyedge.en.alibaba.com/",siteUrl:"http://www.safety-edge.com",tradeContact:"夏慧（监事40%）",tradePhone:"15888072441",createDate:"2026-03-23",origin:"赵孟菲潜在客户（公共）"},
    {name:"宁波市珵翔贸易有限公司",region:"余姚",attr:"A+M-",contact:"方文斌",phone:"15857464118",product:"蜡烛容器、喷雾器、乳液泵、泡沫泵、处理泵、糖浆泵、触发泵、帽子、化妆品管、化妆品瓶",address:"余姚市马渚镇渚北西路39号",source:"赵孟菲资料",platformUrl:"https://nbcxtd.en.alibaba.com/",siteUrl:"",tradeContact:"",tradePhone:"",createDate:"2026-03-12",origin:"赵孟菲潜在客户（公共）"}
  ]
};
