/* YG拜访记录 —— 从 Notion「🏅 YG拜访记录」同步
   导入后：① 写入「拜访客户」时间线；② 对应公司在客户库标记为「已拜访」（不存在则自动建档），可在「已拜访客户」类目查看。 */
window.YG_VISITS = {
  records: [
    {company:"余姚市双宇电器有限公司",date:"2026-06-05",owner:"陈盼",visitor:"杨海媚 陈盼",decider:"劳总",deciderPhone:"13605843333",otherContact:"",otherPhone:"",attr:"A+M-",product:"宠物智能喂食器、宠物智能饮水器",address:"余姚市凤山街道东郊工业园区银翔路5号",source:"和ZCL合作",platform:"",site:"",signed:"未签收",notes:"A：非独立决策人。M：有自己的工厂，业务员3人，宠物用品一年约2.5亿+，之前外贸未做过线上消费。N：在意效果与ROI，关注AI赛道是否适合其行业；已报价79800和99800，签了优惠申请表，需与合伙人商量，18号前回复。T：本月。"},
    {company:"宁波市鄞州籁声进出口有限公司",date:"2026-06-23",owner:"陈丹",visitor:"杨海媚 陈丹",decider:"蒲泳廷",deciderPhone:"13566562531",otherContact:"张小林",otherPhone:"15958847016",attr:"A+M-",product:"低音扬声器、混音器、扬声器配件",address:"鄞州区首南街道鄞县大道东段1299号1201室-5",source:"VLK合作客户",platform:"https://leon-audio.en.alibaba.com",site:"http://leon-audio.com",signed:"未签收",notes:""},
    {company:"宁波恩格精密机械有限公司（宁波溯梦国际贸易有限公司）",date:"2026-05-26",owner:"林朱琦",visitor:"杨海媚",decider:"童总",deciderPhone:"",otherContact:"",otherPhone:"",attr:"A+M-",product:"",address:"",source:"",platform:"",site:"",signed:"未签收",notes:"宁波溯梦国际贸易有限公司，同一体系公司。"},
    {company:"宁波伟铭照明科技有限公司",date:"2026-03-27",owner:"姚子泓",visitor:"杨海媚",decider:"吴伟",deciderPhone:"18906845698",otherContact:"",otherPhone:"",attr:"A+M-",product:"手电筒、LED手电筒、战术手电筒、充电手电筒",address:"奉化区经济开发区滨海新区滨海大道555号滨海万洋众创城E12幢厂房501",source:"资料邀约",platform:"https://wmledlight.en.alibaba.com/",site:"",signed:"已签收",notes:""},
    {company:"宁波开乐亿启电子有限公司",date:"2026-06-10",owner:"杨海媚",visitor:"邹兴涛",decider:"熊智义",deciderPhone:"13957869878",otherContact:"",otherPhone:"",attr:"A+M+",product:"连接器、开关、接线端子、蜂鸣器、保险丝和保险丝座",address:"北仑区霞浦街道荣霞路8-1号",source:"断约老客户",platform:"https://cnkls.en.alibaba.com/",site:"https://www.nbklsele.com/",signed:"已签收",notes:""},
    {company:"宁波横河精密工业股份有限公司",date:"2026-06-03",owner:"杨海媚",visitor:"杨海媚",decider:"",deciderPhone:"",otherContact:"涂经理（采购部经理）",otherPhone:"13306741636",attr:"A-M+",product:"车载空气净化器、智能牙刷、智能扫地机器人、吸尘器、智能厨房",address:"慈溪市新兴产业集群区宗汉街道新兴大道588号",source:"资源分配",platform:"",site:"https://www.mouldcenter.com/",signed:"未签收",notes:""},
    {company:"宁波风尚鸿儒文化用品有限公司",date:"2026-06-15",owner:"杨海媚",visitor:"杨海媚",decider:"毛总",deciderPhone:"13116626655",otherContact:"吴经理",otherPhone:"微信沟通",attr:"A+M-",product:"游戏版、壁炉、茶几、钢琴凳、卫浴搁板、儿童攀爬梯、国际象棋、雷神锤啤酒翘",address:"宁波市奉化区西坞街道虎啸刘村",source:"微信客户",platform:"https://cnnbfs.en.alibaba.com",site:"http://www.zjrisheng.com",signed:"已签收",notes:""},
    {company:"宁波锐信进出口有限公司",date:"2026-06-10",owner:"杨海媚",visitor:"杨海媚",decider:"陈总",deciderPhone:"19523024622",otherContact:"henry",otherPhone:"18367407397",attr:"A+M-",product:"ONU、电缆、配电箱、分路器、跳线",address:"慈溪市坎墩工业园区联飞路255号",source:"微信客户",platform:"https://nbraising.en.alibaba.com/",site:"https://www.nbgsg.com/",signed:"未签收",notes:""},
    {company:"宁波东博新能源有限公司",date:"2026-06-10",owner:"杨海媚",visitor:"杨海媚",decider:"黄丹",deciderPhone:"15824288686",otherContact:"Alice",otherPhone:"18668281331",attr:"A+M+",product:"PVC增塑剂",address:"慈溪市白沙路街道华星黄金大厦15-6室1502号",source:"微信营销",platform:"https://doboenergy.en.alibaba.com/",site:"https://www.dobonewenergy.com/",signed:"未签收",notes:""},
    {company:"宁波北仑睿诺机械有限公司",date:"2026-05-22",owner:"林朱琦",visitor:"杨海媚",decider:"倪华兵",deciderPhone:"18967806755",otherContact:"",otherPhone:"",attr:"A+M+",product:"自行车修理架、自行车车架、车顶行李架",address:"北仑区大碶街道龙潭山路39号12幢1号3楼",source:"部门资料邀约",platform:"https://reynol.en.alibaba.com/",site:"",signed:"未签收",notes:""},
    {company:"舟山市昕达机械有限公司",date:"2026-04-11",owner:"姚子泓",visitor:"杨海媚",decider:"夏总",deciderPhone:"13967231355",otherContact:"",otherPhone:"",attr:"A+M-",product:"锡罐生产线、拧帽生产线、气溶胶锡罐生产线、易开盖生产线、金枪鱼加工线",address:"舟山市定海区舟山港综合保税区迎宾大道68号",source:"资料邀约",platform:"",site:"",signed:"已签收",notes:""},
    {company:"宁波创跃园林工具有限公司",date:"2026-01-14",owner:"杨海媚",visitor:"赵孟菲",decider:"程瀚龙",deciderPhone:"15726830549",otherContact:"",otherPhone:"",attr:"A-M-",product:"对冲修剪机、杆对冲修剪机、真空鼓风机、草修剪机、杆链锯",address:"奉化区锦屏街道盛源路298号",source:"日常邀约",platform:"",site:"https://www.cheery-garden.com/",signed:"未签收",notes:""},
    {company:"宁波腾浪网络通信设备有限公司",date:"2026-01-20",owner:"杨海媚",visitor:"赵孟菲",decider:"王毅勇",deciderPhone:"13806643209",otherContact:"Benson Zhang",otherPhone:"13567889016",attr:"A-M-",product:"PDU、插座、网络机柜、充电推车、桌面插座、开放式机架、橱柜配件、高度可调书桌",address:"慈溪滨海经济开发区镇龙二路673号",source:"日常邀约",platform:"https://turnlink.en.alibaba.com/",site:"https://turn-link.com/",signed:"未签收",notes:""},
    {company:"宁波科盛万向轮有限公司",date:"2026-03-27",owner:"李晶晶",visitor:"杨海媚",decider:"",deciderPhone:"",otherContact:"吴总（副总经理）",otherPhone:"13777195707",attr:"A-M-",product:"脚轮、车轮、支架",address:"余姚市泗门镇镇南村泗马路11号",source:"资料邀约",platform:"https://keshengcaster.en.alibaba.com/",site:"http://www.keshengs.com",signed:"已签收",notes:""},
    {company:"宁波市誉腾精密机械有限公司",date:"2026-06-03",owner:"杨海媚",visitor:"杨海媚",decider:"王总",deciderPhone:"13967869351",otherContact:"",otherPhone:"",attr:"A+M-",product:"注塑机",address:"奉化区莼湖街道朱家店村55号",source:"微信营销转入",platform:"",site:"https://www.yumotomachine.com/",signed:"未签收",notes:""},
    {company:"宁波圣菲机械制造有限公司",date:"2026-06-08",owner:"杨海媚",visitor:"杨海媚",decider:"郑舟",deciderPhone:"13245533366",otherContact:"",otherPhone:"",attr:"A+M+",product:"燃木壁炉、颗粒炉、电壁炉和燃气壁炉",address:"奉化区溪口镇后旺南路1号",source:"微信营销转入",platform:"https://chinaprecise.en.alibaba.com/",site:"https://www.chinaprecise.com/",signed:"未签收",notes:""},
    {company:"宁波爱康铝箔科技有限公司",date:"2026-06-15",owner:"杨海媚",visitor:"杨海媚",decider:"甄总",deciderPhone:"13857885077",otherContact:"",otherPhone:"",attr:"A+M-",product:"航空铝箔容器、烧烤盘、火鸡盘、铝制面包盘等铝箔容器",address:"余姚市永兴东路2号",source:"资料邀约",platform:"",site:"https://www.aluminumfoil-factory.com/",signed:"未签收",notes:""},
    {company:"宁波市豪哲斯贸易有限公司",date:"2026-06-03",owner:"姚子泓",visitor:"姚子泓 卢浩天",decider:"张学成",deciderPhone:"15988662611",otherContact:"",otherPhone:"",attr:"A+M-",product:"水杯",address:"鄞州区高新区华城花园42、50号035幢14-17",source:"白资料",platform:"https://hoz.en.alibaba.com/",site:"http://www.hoznb.com",signed:"未签收",notes:""},
    {company:"余姚市工易仪表有限公司",date:"2026-05-29",owner:"周敏",visitor:"杨海媚",decider:"鲍总（老板女儿）",deciderPhone:"有微信，无电话",otherContact:"周经理",otherPhone:"13586707167",attr:"A+M-",product:"温度控制器、湿度控制器、定时器、温度传感器、温度记录仪",address:"余姚市长庆路9号",source:"其他部门合作",platform:"https://yycj.en.alibaba.com/",site:"https://www.yycj.com/",signed:"未签收",notes:""},
    {company:"慈溪昊城健康科技有限公司",date:"2026-06-13",owner:"姚子泓",visitor:"姚子泓",decider:"余利通",deciderPhone:"13858337554",otherContact:"",otherPhone:"",attr:"A+M-",product:"迷你冰箱、迷你胰岛素冷却冷藏箱、电动水龙头、除湿机",address:"慈溪市观海卫镇工业园西区",source:"公共资料",platform:"",site:"",signed:"未签收",notes:""},
    {company:"宁波洪维光伏科技有限公司",date:"2026-05-26",owner:"杨海媚",visitor:"杨海媚",decider:"刘总",deciderPhone:"13819438167",otherContact:"",otherPhone:"",attr:"A+M-",product:"太阳能板",address:"慈溪市智能家电高新技术产业开发区新兴三路502号16幢1-1、1-2号",source:"微信客户转入",platform:"https://nbhwgf.en.alibaba.com/",site:"https://www.hwsolarpanel.com/",signed:"未签收",notes:""},
    {company:"宁波力升照明电器有限公司",date:"2026-05-19",owner:"杨海媚",visitor:"杨海媚",decider:"",deciderPhone:"",otherContact:"吕佳秋",otherPhone:"13806658803",attr:"A+M-",product:"LED投光灯、LED花园灯、LED高棚灯、工作灯卤素灯、节能工作灯、庭院灯、舱壁灯、工矿照明灯、MH泛光灯",address:"宁海县桥头胡街道益泰路90号",source:"",platform:"",site:"",signed:"未签收",notes:""},
    {company:"宁波工来工往新材料科技有限公司",date:"2026-01-30",owner:"赵孟菲",visitor:"杨海媚、赵孟菲",decider:"季冬冬",deciderPhone:"15968786102",otherContact:"",otherPhone:"",attr:"A-M+",product:"空压机、手动工具、劳保、五金",address:"鄞州启发工业城599号5楼",source:"线上查找",platform:"阿里7个金品站",site:"",signed:"未签收",notes:""},
    {company:"宁波亚晟照明集团有限公司",date:"2026-05-19",owner:"卢浩天",visitor:"杨海媚",decider:"符津逍",deciderPhone:"13777987999",otherContact:"戴总（职业经理人）",otherPhone:"15957445595",attr:"A-M-",product:"LED泛光灯、LED路灯、LED高棚灯、LED高杆灯、LED花园灯",address:"宁海县大佳何镇工业小区",source:"HM合作",platform:"",site:"",signed:"未签收",notes:""},
    {company:"宁波伊特卫浴有限公司",date:"2026-06-03",owner:"杨海媚",visitor:"何松松（主管）",decider:"龚小年",deciderPhone:"15867251717",otherContact:"",otherPhone:"",attr:"A+M-",product:"水龙头、卫浴配件",address:"鄞州区长寿南路555号堇山大厦1706",source:"微信营销转入",platform:"",site:"",signed:"未签收",notes:""},
    {company:"宁波佰誉进出口有限公司",date:"2026-03-05",owner:"杨海媚",visitor:"杨海媚",decider:"张总",deciderPhone:"15356075646",otherContact:"周艳红",otherPhone:"18957450022",attr:"A+M-",product:"工具套装、轴承拆卸器、机械工具、汽车工具、重型卡车专用工具",address:"海曙区集士港镇广昇村华家243号",source:"微信转化",platform:"https://nbbaiyu.en.alibaba.com/",site:"https://www.baiyutools.net/",signed:"已签收",notes:""},
    {company:"宁波可优进出口有限公司",date:"2026-03-06",owner:"杨海媚",visitor:"杨海媚 赵孟菲",decider:"张凰煌",deciderPhone:"13248686522",otherContact:"",otherPhone:"",attr:"A+M-",product:"BTS文具、文件夹、办公文具、艺术家产品、创意产品、家庭装饰",address:"宁波市鄞州区日丽中路555号2904室",source:"白资料邀约",platform:"https://nbkeyou.en.alibaba.com/",site:"http://www.Koyo.com",signed:"未签收",notes:""},
    {company:"宁波易扬贸易有限公司",date:"2026-01-28",owner:"赵孟菲",visitor:"赵孟菲",decider:"刘渊",deciderPhone:"13819830934",otherContact:"",otherPhone:"",attr:"A+M-",product:"紧固件",address:"海曙区解放南路202号建筑大厦9A",source:"线上查找",platform:"",site:"www.easylink.com.tw",signed:"未签收",notes:""},
    {company:"宁波斯派沃通讯设备有限公司",date:"2026-03-05",owner:"赵孟菲",visitor:"杨海媚",decider:"辛小静",deciderPhone:"15267850371",otherContact:"",otherPhone:"",attr:"A+M+",product:"网络机柜、服务器机柜、数据中心、壁柜、室外橱柜、开放式机架、PDU插座、橱柜配件、KVM",address:"鄞州区天童南路535号2807室",source:"白资料邀约",platform:"https://nbstarlink.en.alibaba.com/",site:"https://www.starlink-comm.com/",signed:"已签收",notes:""},
    {company:"浙江美生日化用品有限公司",date:"2026-05-11",owner:"杨海媚",visitor:"杨海媚",decider:"田总",deciderPhone:"15858228282",otherContact:"",otherPhone:"",attr:"A+M-",product:"洗衣液/洗衣凝珠、氧漂白剂/彩漂颗粒、洗碗机清洁剂/洗碗凝珠、多功能清洁片",address:"绍兴市上虞区杭州湾上虞经济技术开发区纬十一路10号",source:"微信客户转入",platform:"",site:"www.mexon.cn",signed:"已签收",notes:""},
    {company:"浙江图乐工业有限公司",date:"2026-03-10",owner:"杨海媚",visitor:"杨海媚",decider:"严凯民",deciderPhone:"13805861487",otherContact:"",otherPhone:"",attr:"A+M-",product:"台式机器、无绳电动工具、电动工具、园艺工具、高压清洗机、空气压缩机、发电机、焊接机、手动工具、水泵",address:"江北区长兴路199号工业物联网研发中心B1208",source:"微信转入",platform:"",site:"https://www.toolucktools.com/",signed:"未签收",notes:""}
  ]
};
